<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GameRoot>$(MSBuildThisFileDirectory)..\Tactical Annihilation</GameRoot>
    <ManagedDir>$(GameRoot)\AnnW_Data\Managed</ManagedDir>
    <BepInExVersion>5.4.23.5</BepInExVersion>
    <BepInExPackageRoot Condition="'$(BepInExPackageRoot)' == ''">$(MSBuildThisFileDirectory).deps\BepInEx_win_x64_$(BepInExVersion)</BepInExPackageRoot>
    <BepInExDir Condition="'$(BepInExDir)' == ''">$(BepInExPackageRoot)\BepInEx\core</BepInExDir>
  </PropertyGroup>
</Project>
