<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>XingyiStarry.Mp.Tests</AssemblyName>
    <RootNamespace>XingyiStarry.Mp.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\..\src\XingyiStarry.Mp.Protocol\XingyiStarry.Mp.Protocol.csproj" /></ItemGroup>
</Project>
